<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.17">
  <POU Name="PRG_Log" Id="{be287b8d-6d84-4fd2-aa5c-09d38f9aeab7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Log
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//-----------------------------------------------------------------------------------------
//
//                  				PRG_Log
//
//								Gestion des Log     			
//-----------------------------------------------------------------------------------------
//
//Auteur: G.GOETZ (inspired by S.MANTZER)
//Création: 04.02.2026
//Dernière modification : 04.02.2026 (G.GOETZ)
//       			
//-----------------------------------------------------------------------------------------
//
//     							Liste des modifications  	
//
// 04.02.2026 (G.GOETZ) -> Création		
//-----------------------------------------------------------------------------------------

(** LOG WM **)
	PRG_LOG_WM();
	]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>